version: 2

project_name: git-cdc

builds:
  - id: git-cdc
    builder: rust
    binary: git-cdc
    command: zigbuild
    flags:
      - --release
      - -p=git-cdc-core
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
  - id: git-cdc-server
    builder: rust
    binary: git-cdc-server
    command: zigbuild
    flags:
      - --release
      - -p=git-cdc-server
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin

archives:
  - id: default
    formats: [tar.gz]
    files:
      - README.md
      - .gitconfig.cdc

checksum:
  name_template: checksums.txt

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Fixes
      regexp: "^fix"
      order: 1
    - title: Other
      order: 999

release:
  draft: false
